CREATE DATABASE censo;
USE censo;

CREATE TABLE departamento(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(200)
);

CREATE TABLE municipio(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(200),
    departamento_id INTEGER,
    FOREIGN KEY (departamento_id) REFERENCES departamento(id)
);

CREATE TABLE resultado(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    sexo VARCHAR(200),
    edad INTEGER,
    nivelEducativo VARCHAR(200),
    departamento_id INTEGER NOT NULL,
    municipio_id INTEGER NOT NULL,
    FOREIGN KEY (municipio_id) REFERENCES municipio(id),
    FOREIGN KEY (departamento_id) REFERENCES departamento(id)
);


INSERT INTO  departamento(nombre) VALUES ('GUATEMALA');
INSERT INTO  departamento(nombre) VALUES ('SACATEP�QUEZ');
INSERT INTO  departamento(nombre) VALUES ('CHIMALTENANGO');
INSERT INTO  departamento(nombre) VALUES ('EL PROGRESO');
INSERT INTO  departamento(nombre) VALUES ('ESCUINTLA');
INSERT INTO  departamento(nombre) VALUES ('SANTA ROSA');
INSERT INTO  departamento(nombre) VALUES ('SOLOL�');
INSERT INTO  departamento(nombre) VALUES ('TOTONICAP�N');
INSERT INTO  departamento(nombre) VALUES ('QUETZALTENANGO');
INSERT INTO  departamento(nombre) VALUES ('SUCHITEP�QUEZ');
INSERT INTO  departamento(nombre) VALUES ('RETALHULEU');
INSERT INTO  departamento(nombre) VALUES ('SAN MARCOS');
INSERT INTO  departamento(nombre) VALUES ('HUEHUETENANGO');
INSERT INTO  departamento(nombre) VALUES ('QUICH�');
INSERT INTO  departamento(nombre) VALUES ('BAJA VERAPAZ');
INSERT INTO  departamento(nombre) VALUES ('ALTA VERAPAZ');
INSERT INTO  departamento(nombre) VALUES ('PETEN');
INSERT INTO  departamento(nombre) VALUES ('IZABAL');
INSERT INTO  departamento(nombre) VALUES ('ZACAPA');
INSERT INTO  departamento(nombre) VALUES ('CHIQUIMULA');
INSERT INTO  departamento(nombre) VALUES ('JALAPA');
INSERT INTO  departamento(nombre) VALUES ('JUTIAPA');

--INSERTO MUNICIPIO

INSERT INTO  municipio(nombre,departamento_id) VALUES ('GUATEMALA','1');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA CATARINA PINULA','1');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JOS� PINULA','1');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JOS� DEL GOLFO','1');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('PALENCIA','1');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CHINAUTLA','1');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN PEDRO AYAMPUC','1');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('MIXCO','1');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN PEDRO SACATEP�QUEZ','1');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JUAN SACATEP�QUEZ','1');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN RAYMUNDO','1');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CHUARRANCHO','1');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('FRAIJANES','1');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('AMATITL�N','1');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('VILLA NUEVA','1');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('VILLA CANALES','1');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN MIGUEL PETAPA','1');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('ALOTENANGO','2');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('ANTIGUA GUATEMALA','2');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CIUDAD VIEJA','2');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('JOCOTENANGO','2');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('MAGDALENA MILPAS ALTAS','2');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('PASTORES','2');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN ANTONIO AGUAS CALIENTES','2');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN BARTOLOM� MILPAS ALTAS','2');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN LUCAS SACATEP�QUEZ','2');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN MIGUEL DUE�AS','2');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA CATARINA BARAHONA','2');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA LUC�A MILPAS ALTAS','2');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA MAR�A DE JES�S','2');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTIAGO SACATEP�QUEZ','2');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTO DOMINGO XENACOJ','2');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SUMPANGO','2');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CHIMALTENANGO','3');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JOS� POAQU�L','3');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN MART�N JILOTEPEQUE','3');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JUAN COMALAPA','3');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA APOLONIA','3');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('TECP�N GUATEMALA','3');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('PATZ�N','3');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('POCHUTA','3');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('PATZIC�A','3');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA CRUZ BALANY�','3');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('ACATENANGO','3');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN PEDRO YEPOCAPA','3');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN ANDR�S ITZAPA','3');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('PARRAMOS','3');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('ZARAGOZA','3');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('EL TEJAR','3');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('GUASTATOYA','4');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('MORAZ�N','4');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN AGUST�N ACASAGUASTL�N','4');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN CRIST�BAL ACASAGUASTL�N','4');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('EL J�CARO','4');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANSARE','4');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANARATE','4');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN ANTONIO LA PAZ','4');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('ESCUINTLA','5');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('GUANAGAZAPA','5');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('IZTAPA','5');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('LA DEMOCRACIA','5');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('LA GOMERA','5');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('MASAGUA','5');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('NUEVA CONCEPCI�N','5');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('PAL�N','5');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('PUERTO SAN JOS�','5');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN VICENTE PACAYA','5');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA LUC�A COTZUMALGUAPA','5');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SIQUINAL�','5');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('TIQUISATE','5');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CUILAPA','6');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CASILLAS','6');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CHIQUIMULILLA','6');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('GUAZACAP�N','6');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('NUEVA SANTA ROSA','6');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('ORATORIO','6');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('PUEBLO NUEVO VI�AS','6');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JUAN TECUACO','6');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN RAFA�L LAS FLORES','6');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA CRUZ NARANJO','6');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA MAR�A IXHUAT�N','6');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA ROSA DE LIMA','6');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('TAXISCO','6');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('BARBERENA','6');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SOLOL�','7');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CONCEPCI�N','7');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('NAHUAL�','7');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('PANAJACHEL','7');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN ANDR�S SEMETABAJ','7');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN ANTONIO PALOP�','7');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JOS� CHACAY�','7');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JUAN LA LAGUNA','7');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN LUCAS TOLIM�N','7');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN MARCOS LA LAGUNA','7');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN PABLO LA LAGUNA','7');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN PEDRO LA LAGUNA','7');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA CATARINA IXTAHUACAN','7');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA CATARINA PALOP�','7');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA CLARA LA LAGUNA','7');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA CRUZ LA LAGUNA','7');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA LUC�A UTATL�N','7');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA MAR�A VISITACI�N','7');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTIAGO ATITL�N','7');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('TOTONICAP�N','8');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('MOMOSTENANGO','8');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN ANDR�S XECUL','8');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN BARTOLO','8');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN CRIST�BAL TOTONICAP�N','8');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN FRANCISCO EL ALTO','8');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA LUC�A LA REFORMA','8');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA MAR�A CHIQUIMULA','8');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('ALMOLONGA','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CABRIC�N','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CAJOL�','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CANTEL','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('COATEPEQUE','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('COLOMBA','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CONCEPCI�N CHIQUIRICHAPA','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('EL PALMAR','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('FLORES COSTA CUCA','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('G�NOVA','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('HUIT�N','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('LA ESPERANZA','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('OLINTEPEQUE','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JUAN OSTUNCALCO','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('PALESTINA DE LOS ALTOS','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('QUETZALTENANGO','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SALCAJ�','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN CARLOS SIJA','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN FRANCISCO LA UNI�N','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN MART�N SACATEP�QUEZ','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN MATEO','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN MIGUEL SIG�IL�','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SIBILIA','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('ZUNIL','9');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('MAZATENANGO','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CHICACAO','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CUYOTENANGO','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('PATULUL','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('PUEBLO NUEVO','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('R�O BRAVO','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAMAYAC','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN ANTONIO','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN BERNARDINO','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JOS� EL �DOLO','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN FRANCISCO ZAPOTITL�N','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN GABRIEL','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JUAN BAUTISTA','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN LORENZO','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN MIGUEL PAN�N','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN PABLO JOCOPILAS','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA BARBARA','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTO DOMINGO','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTO TOMAS LA UNI�N','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('ZUNILITO','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JOS� LA M�QUINA','10');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CHAMPERICO','11');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('EL ASINTAL','11');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('NUEVO SAN CARLOS','11');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('RETALHULEU','11');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN ANDR�S VILLA SECA','11');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN MART�N ZAPOTITL�N','11');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN FELIPE','11');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN SEBASTI�N','11');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA CRUZ MULU�','11');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN MARCOS','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('AYUTLA','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CATARINA','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('COMITANCILLO','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CONCEPCI�N TUTUAPA','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('EL QUETZAL','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('EL RODEO','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('EL TUMBADOR','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('IXCHIGU�N','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('LA REFORMA','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('MALACAT�N','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('NUEVO PROGRESO','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('OC�S','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('PAJAPITA','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('ESQUIPULAS PALO GORDO','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN ANTONIO SACATEP�QUEZ','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN CRIST�BAL CUCHO','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JOS� OJETENAM','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN LORENZO','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN MIGUEL IXTAHUAC�N','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN PABLO','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN PEDRO SACATEP�QUEZ','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN RAFA�L PIE DE LA CUESTA','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SIBINAL','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SIPACAPA','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('TACAN�','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('TAJUMULCO','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('TEJUTLA','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('R�O BLANCO','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('LA BLANCA','12');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('AGUACAT�N','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CHIANTLA','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('COLOTENANGO','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CONCEPCI�N HUISTA','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CUILCO','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('HUEHUETENANGO','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('JACALTENANGO','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('LA DEMOCRACIA','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('LA LIBERTAD','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('MALACATANCITO','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('NENT�N','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN ANTONIO HUISTA','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN GASPAR IXCHIL','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN ILDEFONSO IXTAHUAC�N','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JUAN ATIT�N','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JUAN IXCOY','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN MATEO IXTAT�N','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN MIGUEL ACAT�N','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN PEDRO NECTA','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN PEDRO SOLOMA','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN RAFAEL LA INDEPENDENCIA','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN RAFAEL PETZAL','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN SEBASTI�N COAT�N','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN SEBASTI�N HUEHUETENANGO','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA ANA HUISTA','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA B�RBARA','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA CRUZ BARILLAS','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA EULALIA','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTIAGO CHIMALTENANGO','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('TECTIT�N','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('TODOS SANTOS CUCHUMAT�N','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('UNI�N CANTINIL','13');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA CRUZ DEL QUICH�','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CANILL�','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CHAJUL','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CHICAM�N','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CHICH�','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CHICHICASTENANGO','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CHINIQUE','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CUN�N','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('IXC�N','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('JOYABAJ','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('NEBAJ','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('PACHALUM','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('PATZIT�','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SACAPULAS','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN ANDR�S SAJCABAJ�','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN ANTONIO ILOTENANGO','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN BARTOLOM� JOCOTENANGO','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JUAN COTZAL','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN PEDRO JOCOPILAS','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('USPANT�N','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('ZACUALPA','14');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CUBULCO','15');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA CRUZ EL CHOL','15');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('GRANADOS','15');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('PURULH�','15');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('RABINAL','15');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SALAM�','15');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN MIGUEL CHICAJ','15');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JER�NIMO','15');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('COB�N','16');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN PEDRO CARCH�','16');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JUAN CHAMELCO','16');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN CRIST�BAL VERAPAZ','16');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('TACTIC','16');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('TUCUR�','16');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('TAMAH�','16');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('PANZ�S','16');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SENAH�','16');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CAHAB�N','16');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('LANQU�N','16');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CHAHAL','16');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('FRAY BARTOLOM� DE LAS CASAS','16');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CHISEC','16');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA CRUZ VERAPAZ','16');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA CATALINA LA TINTA','16');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('RAXRUH�','16');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('DOLORES','17');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN BENITO','17');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('FLORES','17');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN FRANCISCO','17');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('LA LIBERTAD','17');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JOS�','17');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('MELCHOR DE MENCOS','17');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN LUIS','17');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('POPT�N','17');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA ANA','17');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN ANDR�S','17');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAYAXCH�','17');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('EL CHAL','17');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('PUERTO BARRIOS','18');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('LIVINGSTON','18');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('EL ESTOR','18');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('MORALES','18');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('LOS AMATES','18');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CABA�AS','19');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('ESTANZUELA','19');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('GUAL�N','19');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('HUIT�','19');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('LA UNI�N','19');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('R�O HONDO','19');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN DIEGO','19');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('TECULUT�N','19');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('USUMATL�N','19');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('ZACAPA','19');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JORGE','19');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CHIQUIMULA','20');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CAMOT�N','20');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CONCEPCI�N LAS MINAS','20');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('ESQUIPULAS','20');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('IPALA','20');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('JOCOT�N','20');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('OLOPA','20');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('QUEZALTEPEQUE','20');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JOS� LA ARADA','20');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JUAN ERMITA','20');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JACINTO','20');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('JALAPA','21');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN PEDRO PINULA','21');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN LUIS JILOTEPEQUE','21');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN MANUEL CHAPARR�N','21');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN CARLOS ALZATATE','21');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('MONJAS','21');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('MATAQUESCUINTLA','21');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('JUTIAPA','22');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('AGUA BLANCA','22');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('ASUNCI�N MITA','22');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('ATESCATEMPA','22');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('COMAPA','22');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('CONGUACO','22');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('EL ADELANTO','22');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('EL PROGRESO','22');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('JALPATAGUA','22');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('JER�Z','22');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('MOYUTA','22');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('PASACO','22');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('QUESADA','22');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SAN JOS� ACATEMPA','22');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('SANTA CATARINA MITA','22');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('YUPILTEPEQUE','22');
INSERT INTO  municipio(nombre,departamento_id) VALUES ('ZAPOTITL�N','22');
