# Use root/example as user/password credentials
version: '3.1'

networks:
    desarrolloweb:
        ipam:
            config:
            - subnet: 192.168.1.0/16

services:

  db:
    image: mysql:5.7
    container_name: mysql57
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
        desarrolloweb:
             ipv4_address: 192.168.1.107
             
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8181:80
    networks:   
    - desarrolloweb
    volumes:
     - /sessions   

    
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
        desarrolloweb:
             ipv4_address: 192.168.1.106

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:   
    - desarrolloweb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
