version: '3.3'

volumes:
  mysql_data:
      driver: local

services:
  mysql:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 'secret'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'secret'
      ports:
      - '3306:3306'
      expose:
      - '3306'
      networks:
      - mysql_network
      volumes:
        - mysql_data:/var/lib/mysql 
      container_name: mysql
networks:
  mysql_network:
      external:
            name: projectdw2019_mongo_net