# Integración de Proyecto Desarrollo Web
version: '3.2'

volumes:
  node_umg:
      driver: local
  mysql_data:
      driver: local

services:
  web:
    container_name: web
    image: docker-node-express-mongoapp
    build: ./node_umg
    command: node src/index.js
    ports:
      - "3000:3000"
    volumes:
      -  node_umg:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "mongo"
    networks:
      redes_data:
          ipv4_address: 172.20.0.12

  mongo:
    container_name: mongo
    image: "mongo"
    ports:
      - "27017:27017"
    networks:
        redes_data:
            ipv4_address: 172.20.0.9

  adminmongo-service:
    image: mrvautin/adminmongo
    restart: "always"
    links: ['mongo:mongo']
    environment:
      - CONN_NAME=whatever
      - DB_HOST=mongo
      - DB_PORT=27017
      - HOST=0.0.0.0
    ports:
      - 1234:1234


networks:
  redes_data:
      external:
            name: redes