server:
  port: 8889


spring:
  application:
    name: book-store
  

  datasource:
    url: jdbc:mysql://172.20.0.3:3306/bookstore?useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
    # url: jdbc:mysql://localhost:3306/bookstore?useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    # password: 12345678
    password: secret
    test-while-idle: true
    validation-query: SELECT 1
    max-wait: 20000
    max-active: 300
    test-on-borrow: true
    platform: mysql
    hikari:
      jdbc-url: jdbc:mysql://172.20.0.3:3306/bookstore?useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
      # jdbc-url: jdbc:mysql://localhost:3306/bookstore?useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
      maximum-pool-size: 400
      idle-timeout: 50000
      max-lifetime: 2400000
      connection-timeout: 60000
      pool-name: mysqlHikariCP
    jackson:
      serialization:
        write-dates-as-timestamps: false
      deserialization:
      # deals with single and multi-valued JWT claims
      accept-single-value-as-array: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.20.0.8:8080/auth/realms/dev
          # issuer-uri: http://192.168.99.100:8080/auth/realms/dev

eureka:
  client:
    serviceUrl:
     # defaultZone: http://192.168.99.100:8761/eureka
      defaultZone: http://172.20.0.5:8761/eureka
      # defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true


# SET GLOBAL max_connections = 25000;
# SHOW VARIABLES LIKE "max_connections";




logging:
  level:
    # root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    #org.springframework.cloud.gateway: DEBUG


