server:
  port: 8889

spring:
  application:
    name: VOTACIONES
  datasource:
    url: jdbc:mysql://localhost:3306/censo?useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 12345678
    test-while-idle: true
    validation-query: SELECT 1 
    max-wait: 20000
    max-active: 300
    test-on-borrow: true
    platform: mysql
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/censo?useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
      maximum-pool-size: 400
      idle-timeout: 50000
      max-lifetime: 2400000
      connection-timeout: 60000
      pool-name: MyPoll
      
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      accept-single-value-as-array: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.20.0.8:8080/auth/realms/dev


logging:
  level:
    root: DEBUG
    # org.springframework.web: info
    # org.springframework.security: info
    # org.springframework.security.oauth2: info