# Integración de Proyecto Desarrollo Web
version: '3.2'

volumes:
  keycloak_data:
      driver: local
  mysql_data:
      driver: local

services:
  eureka:
    container_name: eureka_server
    image: eureka
    privileged: true
    build:
        context: ./Eureka
        dockerfile: Dockerfile
    ports:
      - "8761:8761"

  redis:
    container_name: some-redis
    image: redis
    ports: 
      - "6379:6379"
    

  # gateway:
  #   container_name: gateway
  #   image: gateway2
  #   privileged: true
  #   build:
  #       context: ./Gateway
  #       dockerfile: Dockerfile
  #   ports:
  #     - "8887:8887"
  #   depends_on:
  #     - redis

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    # networks:
    #   - keycloak_network

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8080:8080
    # networks:
    #   - keycloak_network
    depends_on:
      - postgres

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # networks:   
    # - redes

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    # networks:   
    # - redes
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      
  db:
    image: mysql:5.7
    container_name: mysql57
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql 
    # networks:
    #     desarrolloweb:
    #          ipv4_address: 192.168.1.107
             
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8181:80
    volumes:
     - sessions  
# networks:
#   bridge:
#       external:
#             name: bridge